import './style.css';
import { initialState, currentSession, setSession, sessionKey, migrateState, stats, makeSession, grade, dayKey, nextCard, intervalLabel, acceptsReading, parseWordImport, validateBackup } from './core.js';
import { openDB, readState, saveState } from './storage.js';
import { kanaRows, yoon } from './kana.js';

const $=s=>document.querySelector(s), app=$('#app'), modal=$('#modal');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z',books:'M12 5v16M12 5C8 2 4 3 2 4v15c4-2 7-1 10 2 3-3 6-4 10-2V4c-2-1-6-2-10 1Z',star:'m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2L12 17.3l-5.6 2.9 1.1-6.2L3 9.6l6.2-.9Z',settings:'M4 7h16M4 17h16M8 4v6M16 14v6',arrow:'M5 12h14m-6-6 6 6-6 6',back:'m14 6-6 6 6 6',sound:'M11 5 6 9H3v6h3l5 4ZM15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14',headphones:'M4 14v-3a8 8 0 0 1 16 0v3M4 12H2v8h4v-8Zm16 0h2v8h-4v-8Z',write:'m15 4 5 5M4 20l5-1L21 7l-5-5L4 14Z',check:'m5 12 4 4L19 6',close:'m6 6 12 12M6 18 18 6',search:'M20 20l-5-5M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0Z',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',upload:'M12 16V4m-5 5 5-5 5 5M4 16v5h16v-5',chart:'M4 20V10m8 10V4m8 16v-7',sun:'M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z',leaf:'M4 20c9 0 16-5 16-16C9 4 4 9 4 20Zm0 0L15 9',undo:'M4 9h10a6 6 0 0 1 0 12M4 9l5-5M4 9l5 5',phone:'M7 2h10a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2ZM11 18h2'};
function icon(name){return `<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[name]||paths.leaf}"/></svg>`;}
function btn(label,action,cls='',attrs=''){return `<button class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;}
let state,baseWords=[],baseBooks=[],words=[],byId=new Map(),page='home',revealed=false,spellingResult=null,lastState=null,busy=false,notebookFilter='favorites',bookFilter='all',search='',limit=60,kanaType='h',kanaQuiz=null,offlineStatus='正在检查离线状态',speech,toastTimer;
const channel='BroadcastChannel' in window?new BroadcastChannel('kotoba-changes'):null;
let stale=false;
channel?.addEventListener('message',()=>{stale=true;toast('另一个窗口更新了学习记录，请重新打开本页后继续');});
function refreshWords(){words=[...baseWords,...state.customWords];byId=new Map(words.map(w=>[w.id,w]));}
function books(){return [...baseBooks,...state.customBooks.map(b=>({...b,kanji:'私',description:'自己的词书',count:state.customWords.filter(w=>w.book===b.id).length}))];}
function currentBook(){return books().find(b=>b.id===state.settings.book)||books()[0];}
function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4000);}
async function commit(draft){if(stale)throw new Error('另一窗口已保存新记录，请刷新本页，避免覆盖');await saveState(draft);state=draft;channel?.postMessage('changed');}
function showDialog(html){modal.innerHTML=`<div class="modal-head">${btn(icon('close'),'close','icon-button','aria-label="关闭"')}</div>${html}`;if(!modal.open)modal.showModal();}
function openInfo(title,text){showDialog(`<h2>${esc(title)}</h2><p>${esc(text)}</p>${btn('知道了','close','primary full')}`);}
function nav(){return `<nav class="nav" aria-label="主导航">${[['home','home','今日'],['books','books','词书'],['notebook','star','单词本'],['settings','settings','我的']].map(([id,i,t])=>btn(`${icon(i)}<span>${t}</span>`,'page',page===id?'active':'',`data-page="${id}" ${page===id?'aria-current="page"':''}`)).join('')}</nav>`;}
function shell(content,title,sub=''){return `<aside class="sidebar"><a href="#home" class="brand"><img src="/icon.svg" alt=""/>言叶<span>KOTOBA</span></a><p class="side-copy">让日语，<br>慢慢成为日常。</p><div class="side-bottom">ひとつ、ひとつ。<br><span>你的日语学习空间</span></div></aside><main class="main ${page==='home'?'home-main':''}"><header class="topbar"><div><span class="eyebrow">${esc(sub||'KOTOBA · JAPANESE')}</span><h1>${esc(title)}</h1></div>${btn(icon('chart'),'page','icon-button','data-page="stats" aria-label="学习统计"')}</header>${content}</main>${nav()}`;}
function landscape(){return `<svg class="landscape" viewBox="0 0 900 440" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><defs><linearGradient id="mount" x2="0" y2="1"><stop stop-color="#43605e" stop-opacity=".6"/><stop offset="1" stop-color="#243c3d"/></linearGradient></defs><circle cx="700" cy="85" r="36" fill="#e4edcf" opacity=".8"/><path d="M0 290 125 213 215 253 363 157 525 255 634 206 780 272 900 210V440H0Z" fill="url(#mount)"/><path d="M0 320 98 293 235 337 411 271 565 327 714 280 900 360V440H0Z" fill="#263f3d"/><path d="M0 382Q145 299 357 375T900 345V440H0Z" fill="#1d3534"/><g fill="none" stroke="#9cac91" stroke-opacity=".12"><path d="M-60 400Q150 285 375 381T970 326"/><path d="M-60 421Q150 306 375 402T970 347"/><path d="M-60 442Q150 327 375 423T970 368"/></g></svg>`;}
function home(){
  const s=stats(state,words),b=currentBook(),learned=words.filter(w=>w.book===b.id&&state.cards[w.id]).length,pct=Math.round(learned/b.count*100)||0;
  const date=new Date(),featured=baseWords.find(w=>w.word==='木漏れ日')||baseWords.find(w=>w.word==='日々')||baseWords[0];
  return shell(`<section class="hero">${landscape()}<div class="hero-top"><span>今日も、少しずつ。</span><span>${date.getMonth()+1} / ${String(date.getDate()).padStart(2,'0')}</span></div><div class="hero-word"><span class="eyebrow">今日のことば</span><h2 lang="ja">${esc(featured.word)}</h2><div lang="ja">${esc(featured.reading)} ${btn(icon('sound'),'speak','hero-sound',`data-id="${featured.id}" aria-label="朗读每日单词"`)}</div><p>${esc(featured.meaning)}</p></div><div class="hero-bottom"><span>${icon('leaf')} 每一个词，都让世界更近一点。</span><span>KOTOBA / 01</span></div></section>
  <div class="home-grid"><section class="panel plan"><div class="section-title"><h2>今天，学一点日语</h2>${btn('调整计划','page','text-button','data-page="settings"')}</div><div class="daily-numbers"><div><span>新词</span><strong>${s.newToday}<small> / ${state.settings.goal}</small></strong><p>今日已学</p></div><div><span>待复习</span><strong>${s.due.length}</strong><p>按记忆情况安排</p></div><div class="ring" style="--progress:${Math.min(100,s.newToday/state.settings.goal*100)}%"><span>${Math.round(Math.min(100,s.newToday/state.settings.goal*100))}<small>%</small></span></div></div>
  ${state.session?.queue.length?btn(`继续上次学习 <small>剩余 ${state.session.queue.length} 词</small>${icon('arrow')}`,'resume','primary full','data-key="study"'):btn(`${s.newToday>=state.settings.goal?'继续学新词':'开始学新词'} ${icon(s.newToday>=state.settings.goal?'check':'arrow')}`,'start','primary full','data-kind="learn"')}
  ${btn(`复习旧词 <span>${s.due.length?`${s.due.length} 词等待复习`:'暂时没有到期单词'}</span>${icon('arrow')}`,'start','secondary full','data-kind="review"')}
  <p class="quiet center">${s.streak?`已经连续学习 ${s.streak} 天，保持自己的节奏。`:'不用急，从今天的第一个词开始。'}</p></section>
  <section class="panel book-current"><div class="section-title"><h2>正在学习</h2>${btn('换本词书','page','text-button','data-page="books"')}</div><div class="current-book-row"><div class="book-cover ${b.id}"><small>${esc(b.id.startsWith('custom')?'MY BOOK':b.id)}</small><strong>${esc(b.kanji)}</strong><span>日本語</span></div><div><span class="eyebrow">${esc(b.id.startsWith('custom')?'CUSTOM':'JLPT '+b.id)}</span><h3>${esc(b.name)}</h3><p>${b.count.toLocaleString()} 词 · 中文释义</p><div class="progress"><i style="width:${pct}%"></i></div><p class="quiet">已学 ${learned} / ${b.count} 词 · ${pct}%</p></div></div><div class="practice-buttons">${btn(`${icon('headphones')}${state.practiceSessions?.['practice-listen']?.queue.length?'继续听音辨词':'听音辨词'}`,'start','','data-kind="practice" data-mode="listen"')}${btn(`${icon('write')}${state.practiceSessions?.['practice-write']?.queue.length?'继续假名拼写':'假名拼写'}`,'start','','data-kind="practice" data-mode="write"')}</div></section></div>
  <section class="kana-banner"><div><span class="kana-mark" lang="ja">あ</span><div><h3>初次见面，五十音</h3><p>平假名、片假名，从这里起步</p></div></div>${btn(icon('arrow'),'page','icon-button','data-page="kana" aria-label="打开五十音"')}</section>`,'今日',new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(date));
}
function booksPage(){return shell(`<p class="intro">从初识到熟悉，找到适合自己的那一本。</p><div class="books-grid">${books().map(b=>{const n=words.filter(w=>w.book===b.id&&state.cards[w.id]).length;return `<article class="book-tile panel"><div class="book-cover large ${b.id}"><small>${esc(b.id.startsWith('custom')?'MY BOOK':b.id)}</small><strong lang="ja">${esc(b.kanji)}</strong><span>日本語 · 言葉を集める</span></div><div class="book-info"><div class="section-title"><h2>${esc(b.name)}</h2>${b.id===state.settings.book?'<span class="badge green">正在学</span>':''}</div><p>${esc(b.description)}</p><p class="quiet">${b.count.toLocaleString()} 词 · 已学 ${n}</p><div class="progress"><i style="width:${n/b.count*100}%"></i></div><div class="book-actions">${btn(b.id===state.settings.book?'继续学习':'选为学习词书','select-book','primary',`data-id="${b.id}"`)}${btn('浏览','browse-book','secondary',`data-id="${b.id}"`)}</div></div></article>`;}).join('')}</div><section class="panel import-panel"><div><h3>带上自己的词书</h3><p>支持 CSV / JSON，导入后可离线学习。</p></div>${btn(`${icon('upload')} 导入词书`,'import-book','secondary')}</section><p class="quiet">JLPT 分级采用社区整理，并非官方完整考纲。词书由 egg rolls 制作，CC BY-NC 4.0，仅限非商业使用。${btn('查看来源','sources','text-button')}</p>`,'词书','YOUR LITTLE LIBRARY');}
function wordRows(list){return list.map(w=>`<button class="word-row" data-action="word-detail" data-id="${w.id}"><span class="word-row-main"><strong lang="ja">${esc(w.word)}</strong><small lang="ja">${esc(w.reading)}</small></span><span class="word-row-meaning">${esc(w.meaning)}</span><span class="word-row-meta">${state.favorites.includes(w.id)?icon('star'):''}<small>${esc(w.book.startsWith('custom')?'自选':w.book)}</small></span></button>`).join('');}
function filteredWords(){const due=new Set(stats(state,words).due);return words.filter(w=>(bookFilter==='all'||w.book===bookFilter)&&(notebookFilter==='all'||notebookFilter==='favorites'&&state.favorites.includes(w.id)||notebookFilter==='learned'&&state.cards[w.id]||notebookFilter==='due'&&due.has(w.id))&&(!search||[w.word,w.reading,w.meaning].some(t=>t.toLowerCase().includes(search.toLowerCase()))));}
function listBody(){const list=filteredWords();return `<div class="section-title"><p class="quiet">${list.length.toLocaleString()} 个单词</p>${notebookFilter==='favorites'&&list.length?btn('练习收藏','start','text-button','data-kind="favorites"'):''}</div>${list.length?`<div class="word-list">${wordRows(list.slice(0,limit))}</div>${list.length>limit?btn(`继续显示（${limit} / ${list.length}）`,'more','secondary full'):''}`:`<div class="empty">${icon(notebookFilter==='favorites'?'star':'search')}<h3>${search?'没有找到这个词':'这里还没有单词'}</h3><p>${search?'试试日语、假名或中文关键词。':notebookFilter==='favorites'?'在学习卡片上点一下星标，把想记住的词留在这里。':'开始学习后，你的足迹会出现在这里。'}</p>${btn('去学几个新词','page','secondary','data-page="home"')}</div>`}`;}
function notebook(){return shell(`<div class="search-box">${icon('search')}<input id="search" type="search" aria-label="搜索单词" placeholder="搜索日语、假名或中文" value="${esc(search)}" autocomplete="off"/></div><div class="filter-row"><div class="tabs">${[['favorites','收藏'],['learned','已学'],['due','待复习'],['all','全部']].map(([id,label])=>btn(label,'filter',notebookFilter===id?'selected':'',`data-filter="${id}" aria-pressed="${notebookFilter===id}"`)).join('')}</div><select id="book-filter" aria-label="筛选词书"><option value="all">全部词书</option>${books().map(b=>`<option value="${b.id}" ${bookFilter===b.id?'selected':''}>${esc(b.name)}</option>`).join('')}</select></div><div id="list-body">${listBody()}</div>`,'单词本','WORDS THAT STAY');}
function examplesHTML(w){return w.examples?.length?`<section class="examples"><div class="section-title"><h3>在语境中记住</h3><span class="quiet">例句与关联表达</span></div>${w.examples.map((e,i)=>`<article class="example"><div class="example-ja"><p lang="ja">${highlight(e.ja,w.word)}</p>${btn(icon('sound'),'speak','icon-button',`data-id="${w.id}" data-example="${i}" aria-label="朗读第 ${i+1} 条例句"`)}</div><p>${esc(e.zh)}</p>${e.furigana&&e.furigana!==e.ja?`<details><summary>查看注音</summary><p lang="ja" class="furigana">${esc(e.furigana)}</p></details>`:''}</article>`).join('')}</section>`:'<p class="quiet">这条自选词暂时没有例句，可以在笔记里补充。</p>';}
function highlight(text,word){return esc(text).split(esc(word)).join(`<mark>${esc(word)}</mark>`);}
function detail(w){const c=state.cards[w.id];showDialog(`<div class="detail-heading"><span class="badge">${esc(w.book.startsWith('custom')?'我的词书':w.book)}</span>${btn(icon('star'),'favorite',`icon-button ${state.favorites.includes(w.id)?'is-favorite':''}`,`data-id="${w.id}" aria-label="${state.favorites.includes(w.id)?'取消收藏':'收藏单词'}" aria-pressed="${state.favorites.includes(w.id)}"`)}</div><h2 class="detail-word" lang="ja">${esc(w.word)}</h2><p class="reading" lang="ja">${esc(w.reading)} <span>${esc(w.accent)}</span> ${btn(icon('sound'),'speak','icon-button',`data-id="${w.id}" aria-label="朗读单词"`)}</p><p class="meaning"><span class="pos">${esc(w.pos)}</span>${esc(w.meaning)}</p>${examplesHTML(w)}<label class="note-label" for="word-note">我的笔记</label><textarea id="word-note" maxlength="5000" placeholder="写下联想、用法，或自己的例句…">${esc(state.notes[w.id]||'')}</textarea>${btn('保存笔记','save-note','secondary full',`data-id="${w.id}"`)}<p class="quiet">${c?`已回答 ${c.reps} 次 · 下次复习 ${new Date(c.due).toLocaleString('zh-CN')}`:'尚未学习'}<br>词条来源：${esc(w.source||'用户导入')}</p>`);}
function study(){
 const ss=currentSession(state);if(!ss)return home();if(!ss.queue.length)return completed();const w=byId.get(ss.queue[0]);if(!w)return '<p>词条缺失，请从首页重新开始。</p>';
 const practice=['practice','favorites'].includes(ss.kind),listen=ss.mode==='listen',write=ss.mode==='write';
 const now=new Date();
 return `<main class="study"><header class="study-header">${btn(icon('close'),'exit-study','icon-button','aria-label="暂停学习"')}<div><strong>${practice?'专项练习':ss.kind==='review'?'复习旧词':'学习新词'}</strong><span>${ss.completed} / ${ss.total}</span></div>${btn(icon('star'),'favorite',`icon-button ${state.favorites.includes(w.id)?'is-favorite':''}`,`data-id="${w.id}" aria-label="${state.favorites.includes(w.id)?'取消收藏':'收藏单词'}" aria-pressed="${state.favorites.includes(w.id)}"`)}</header><div class="progress study-progress"><i style="width:${ss.completed/ss.total*100}%"></i></div><div class="study-content"><div class="study-meta"><span class="badge">${esc(w.book.startsWith('custom')?'自选':w.book)}</span><span>${practice?'练习不改变复习计划':state.cards[w.id]?'再次见面':'初次见面'}</span>${btn(icon('undo'),'undo','icon-button',`aria-label="撤销上次评分" ${lastState?'':'disabled'}`)}</div>
 <section class="word-stage ${listen&&!revealed?'listening':''}" ${!write||revealed?'data-audio-area':''}>${listen&&!revealed?`${btn(icon('headphones'),'speak','listen-orb',`data-id="${w.id}" aria-label="播放待辨认单词"`)}<h2>听见了哪个词？</h2><p>点击播放，在心里想一想它的意思。</p>`:write&&!revealed?`<span class="eyebrow">写出这个词的假名</span><h2 class="write-prompt">${esc(w.meaning)}</h2><form id="spelling-form"><input id="spelling" lang="ja" aria-label="输入假名" placeholder="在这里输入假名" autocomplete="off" autocapitalize="off" spellcheck="false"/><button type="submit" class="secondary">检查答案 ${icon('arrow')}</button></form><p class="quiet">支持平假名或片假名 · 可使用日语键盘</p>`:`<h1 lang="ja" class="study-word ${w.word.length>8?'long':''}">${esc(w.word)}</h1><div class="reading" lang="ja">${revealed||state.settings.showReading?esc(w.reading):btn('显示假名','reading','text-button')} ${revealed?`<span class="accent" title="声调标记">${esc(w.accent)}</span>`:''}${btn(icon('sound'),'speak','icon-button',`data-id="${w.id}" aria-label="朗读当前单词"`)}</div>`}
 ${revealed?`<p class="meaning"><span class="pos">${esc(w.pos)}</span>${esc(w.meaning)}</p>${spellingResult!==null?`<p class="answer-feedback ${spellingResult?'correct':'wrong'}">${spellingResult?'✓ 假名写对了':'再看一眼正确假名，把读音记下来。'}</p>`:''}`:''}</section>
 ${revealed?`${examplesHTML(w)}${w.extra?`<details class="extra"><summary>补充解释</summary><p lang="ja">${esc(w.extra)}</p></details>`:''}<div class="word-footer">${btn(`${icon('write')} 笔记${state.notes[w.id]?' · 已记录':''}`,'word-detail','text-button',`data-id="${w.id}"`)}<span>词条 · ${esc(w.source||'用户导入')}</span></div>`:`<div class="recall-hint" ${!write?'data-audio-area':''}><span>思い出してみよう</span><p>给记忆留一点时间。</p></div>`}</div>
 <footer class="study-controls">${revealed?`<p class="quiet center">${practice?'这一次，你记住了吗？':'如实选择，安排下次复习'}</p><div class="rating-grid">${[[1,'忘记了','again'],[2,'有点模糊','hard'],[3,'记住了','good'],[4,'很熟悉','easy']].map(([r,t,c])=>btn(`<strong>${t}</strong><small>${practice?'继续':intervalLabel(nextCard(state.cards[w.id],r,now).card,now)}</small>`,'grade',c,`data-rating="${r}"`)).join('')}</div>`:btn(`${write?'直接看答案':'查看释义'} ${icon('arrow')}`,'reveal','primary full')}<div class="keyboard-hint">${revealed?'键盘 1–4 评分':'空格查看释义'} · ${practice?'练习模式':'进度自动保存'}</div></footer></main>`;
}
function completed(){const ss=currentSession(state),practice=['practice','favorites'].includes(ss.kind);return `<main class="completion"><div class="completion-icon">${icon('check')}</div><span class="eyebrow">少しずつ、前へ。</span><h1>又向前走了一点。</h1><p>${practice?'本次专项练习完成':'这一组单词，已经留在你的记忆里。'}</p><div class="completion-stats"><div><strong>${ss.total}</strong><span>完成词数</span></div><div><strong>${ss.answered}</strong><span>回想次数</span></div></div><p class="quiet">${practice?'专项练习不会改变正式复习计划。':'学习记录已保存在本机，下次复习见。'}</p>${btn(practice?'再练一组':'继续学新词','start','primary full',`data-kind="${practice?ss.kind:'learn'}" data-mode="${practice?ss.mode:'recognize'}"`)}${btn('回到今日','finish','secondary full')}${lastState?btn('撤销最后一次评分','undo','text-button'):''}</main>`;}
function statsPage(){const s=stats(state,words),days=Array.from({length:28},(_,i)=>{const d=new Date();d.setDate(d.getDate()-27+i);return dayKey(d);});const counts=Object.fromEntries(days.map(d=>[d,state.logs.filter(l=>l.day===d).length]));return shell(`<div class="stat-tiles">${[[s.learned,'累计学过'],[s.mastered,'长期记住'],[s.streak,'连续学习天数'],[s.answersToday,'今日回想次数']].map(([n,t])=>`<div class="panel"><strong>${n.toLocaleString()}</strong><span>${t}</span></div>`).join('')}</div><section class="panel"><div class="section-title"><h2>每一天，都算数</h2><span class="quiet">最近 28 天</span></div><div class="heatmap">${days.map(d=>`<div class="heat-cell level-${Math.min(4,Math.ceil(counts[d]/15))}" title="${d}：${counts[d]} 次" aria-label="${d} 回想 ${counts[d]} 次"><span>${Number(d.slice(-2))}</span></div>`).join('')}</div><p class="quiet">深浅代表当天回想次数。长期记住：复习间隔达到 21 天的单词。</p></section><section class="panel"><h2>接下来 7 天</h2><div class="forecast">${Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);const n=Object.values(state.cards).filter(c=>dayKey(c.due)===dayKey(d)).length;return `<div><strong>${n}</strong><span>${i===0?'今天':`${d.getMonth()+1}/${d.getDate()}`}</span></div>`;}).join('')}</div><p class="quiet">根据目前的复习计划估算，回答后会更新；逾期单词见首页“待复习”。</p></section>`,'学习足迹','A LITTLE EVERY DAY');}
function settings(){const voices=getVoices();return shell(`<section class="panel setting-panel"><h2>自己的节奏</h2><label class="setting-row"><span>每日新词<small>复习单独安排，不受新词上限影响</small></span><select id="goal">${[5,10,15,20,30,40,50,100,...([5,10,15,20,30,40,50,100].includes(state.settings.goal)?[]:[state.settings.goal])].sort((a,b)=>a-b).map(n=>`<option value="${n}" ${n===state.settings.goal?'selected':''}>${n} 词</option>`).join('')}</select></label><label class="setting-row"><span>卡片显示假名<small>关闭后先尝试自己回想读音</small></span><input type="checkbox" id="showReading" role="switch" ${state.settings.showReading?'checked':''}/></label><label class="setting-row"><span>自动朗读单词</span><input type="checkbox" id="autoAudio" role="switch" ${state.settings.autoAudio?'checked':''}/></label><label class="setting-row"><span>夜间模式</span><input type="checkbox" id="theme" role="switch" ${state.settings.theme==='dark'?'checked':''}/></label></section>
 <section class="panel setting-panel"><h2>声音</h2><label class="setting-row"><span>日语语音</span><select id="voice"><option value="">自动选择日语语音</option>${voices.map(v=>`<option value="${esc(v.voiceURI)}" ${state.settings.voice===v.voiceURI?'selected':''}>${esc(v.name)}${v.localService?' · 本机':''}</option>`).join('')}</select></label><label class="setting-row"><span>朗读速度</span><select id="rate">${[0.6,0.75,0.85,1,1.15,...([0.6,0.75,0.85,1,1.15].includes(state.settings.rate)?[]:[state.settings.rate])].sort((a,b)=>a-b).map(n=>`<option value="${n}" ${state.settings.rate===n?'selected':''}>${n} ×</option>`).join('')}</select></label>${btn(`${icon('sound')} 试听日语`,'test-voice','secondary')}<p class="quiet">使用设备的日语合成语音。离线发音取决于系统是否已下载日语语音；不保证还原词典声调，请同时参考声调标记。</p></section>
 <section class="panel setting-panel"><h2>离线与数据</h2><div class="setting-row"><span>离线状态<small id="offline-status">${esc(offlineStatus)}</small></span>${btn('检查','check-offline','text-button')}</div><div class="setting-row"><span>安装到 iPhone<small>添加主屏幕后，在应用内确认离线已就绪</small></span>${btn(icon('phone'),'install-help','icon-button','aria-label="iPhone 安装帮助"')}</div><div class="backup-buttons">${btn(`${icon('download')} 导出备份`,'export','secondary')}${btn(`${icon('upload')} 恢复备份`,'restore','secondary')}</div><p class="quiet">记录只保存在当前设备和访问地址，不自动跨设备同步。定期导出到“文件”；清理网站数据或更换地址前先备份。</p></section>
 <section class="panel about"><img src="/icon.svg" alt="言叶图标"/><h2>言叶 <span>1.0</span></h2><p>让日语一点点变成日常。</p>${btn('词库来源与开源许可','sources','text-button')}</section>`,'我的','MAKE IT YOURS');}
function kanaPage(){return shell(`<div class="section-title"><p class="intro">先认识声音，再认识世界。</p>${btn('随机测一测','kana-quiz','secondary')}</div><div class="tabs kana-tabs">${btn('平假名','kana-type',kanaType==='h'?'selected':'','data-type="h"')}${btn('片假名','kana-type',kanaType==='k'?'selected':'','data-type="k"')}</div><section class="panel"><h2>清音</h2><p class="quiet">点击假名听发音 · 下方为罗马字</p><div class="kana-grid">${kanaRows.slice(0,11).flat().map(k=>k?btn(`<strong lang="ja">${k[kanaType]}</strong><small>${k.r}</small>`,'kana-speak','kana-cell',`data-text="${k[kanaType]}" aria-label="${k[kanaType]} ${k.r}"`):'<span></span>').join('')}</div></section><section class="panel"><h2>浊音与半浊音</h2><div class="kana-grid">${kanaRows.slice(11).flat().map(k=>btn(`<strong lang="ja">${k[kanaType]}</strong><small>${k.r}</small>`,'kana-speak','kana-cell',`data-text="${k[kanaType]}"`)).join('')}</div></section><section class="panel"><h2>拗音</h2><p class="quiet">小写的 ゃ・ゅ・ょ 与前一个音一起读作一拍。</p><div class="kana-grid yoon">${yoon.map(k=>btn(`<strong lang="ja">${k[kanaType]}</strong><small>${k.r}</small>`,'kana-speak','kana-cell',`data-text="${k[kanaType]}"`)).join('')}</div></section><section class="panel"><h2>也别忘了这些声音</h2><p>小「っ」表示促音，停顿一拍，如「きって」。长音要多读一拍，如「おばあさん」「コーヒー」。助词「は」「へ」「を」分别读作 wa、e、o。</p></section>`,'五十音','はじめまして');}
function getVoices(){return 'speechSynthesis' in window?speechSynthesis.getVoices().filter(v=>/^ja(?:[-_]|$)/i.test(v.lang)):[];}
function speak(text){if(!('speechSynthesis'in window)){toast('此浏览器不支持语音，请使用 Safari');return;}const voices=getVoices();if(!voices.length){toast('尚未找到日语语音，请在 iPhone 辅助功能的朗读语音中下载日语后重试');return;}speechSynthesis.cancel();speech=new SpeechSynthesisUtterance(text);speech.lang='ja-JP';speech.rate=state.settings.rate;speech.voice=voices.find(v=>v.voiceURI===state.settings.voice)||voices.find(v=>v.localService)||voices[0];speech.onerror=e=>{if(!['interrupted','canceled'].includes(e.error))toast('语音播放失败，请检查日语语音是否已下载');};speechSynthesis.speak(speech);}
function stopSpeech(){if('speechSynthesis'in window)speechSynthesis.cancel();}
function render(){document.documentElement.dataset.theme=state.settings.theme;app.innerHTML=page==='study'?study():page==='books'?booksPage():page==='notebook'?notebook():page==='settings'?settings():page==='stats'?statsPage():page==='kana'?kanaPage():home();}
function go(p){stopSpeech();if(p!=='study')lastState=null;page=p;revealed=false;spellingResult=null;location.hash=p;render();window.scrollTo(0,0);}
async function resumeSession(key='study'){
 await commit({...state,activeSessionKey:key});lastState=null;modal.close();go('study');autoSpeak();
}
async function start(kind,mode='recognize'){
 const key=sessionKey(kind,mode),existing=key==='study'?state.session:state.practiceSessions?.[key];
 const proceed=async()=>{const session=makeSession(state,words,kind,mode);if(!session){openInfo(kind==='review'?'复习暂时完成':'这本词书已经学完',kind==='review'?'现在没有到期单词，稍后回来会按记忆情况安排下一次复习。':'可以换一本词书，或者练习已学单词。');return;}await commit(setSession(state,key,session));lastState=null;modal.close();go('study');autoSpeak();};
 if(existing?.queue.length){
   if(existing.kind===kind&&existing.mode===mode){await resumeSession(key);return;}
   showDialog(`<h2>上次还有 ${existing.queue.length} 词</h2><p>可以接着学，也可以开始新的任务。已经学过的记录会保留。</p>${btn('继续上次学习','resume','primary full',`data-key="${key}"`)}${btn('开始新的任务','replace-session','secondary full')}`);pendingStart=proceed;
 }else await proceed();
}
let pendingStart=null;
function autoSpeak(){const ss=currentSession(state);if(state.settings.autoAudio&&page==='study'&&ss?.queue.length&&ss.mode!=='write')speak(byId.get(ss.queue[0]).reading);}
async function exportBackup(){const text=JSON.stringify({app:'kotoba-local',version:1,exportedAt:new Date().toISOString(),state},null,2);const file=new File([text],`言叶备份-${dayKey()}.json`,{type:'application/json'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:'言叶学习备份'});return;}catch(e){if(e.name==='AbortError')return;}}const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('备份已生成，请保存到“文件”');}
function pickFile(accept,handler){const input=document.createElement('input');input.type='file';input.accept=accept;input.addEventListener('change',async()=>{try{const file=input.files[0];if(!file)return;if(file.size>50*1024*1024)throw new Error('文件超过 50 MB，请分成更小的文件');await handler(file,await file.text());}catch(e){toast(e.message);}});input.click();}
let pendingImport=null,pendingRestore=null;
function sourceDialog(){showDialog(`<h2>词库来源与许可</h2><p><strong>egg rolls · JLPT N1–N5</strong><br>10,641 词，18,191 条例句或关联表达。社区分级，可能存在疏漏。</p><p><a href="https://github.com/5mdld/anki-jlpt-decks" target="_blank" rel="noopener">GitHub 原项目 ↗</a> · <a href="/licenses/eggrolls-CC-BY-NC-4.0.txt" target="_blank">CC BY-NC 4.0</a></p><p>本应用将 Anki 文本导出转换为 JSON，保留日语、简体中文、假名、声调与例句，移除原 HTML 和音频引用，并按原词表序号排序。仅供非商业使用。音频使用设备语音合成，并非原牌组的录音。</p><p><strong>复习算法：ts-fsrs 5.4.2</strong><br><a href="https://github.com/open-spaced-repetition/ts-fsrs" target="_blank" rel="noopener">Open Spaced Repetition ↗</a> · <a href="/licenses/ts-fsrs-MIT.txt" target="_blank">MIT 许可</a></p><p>应用界面、图标和插画为本项目制作。</p>`);}
function installDialog(){showDialog(`<h2>装进 iPhone</h2><ol><li>首次安装时，电脑和手机连接同一 Wi-Fi。在电脑上打开“启动言叶.cmd”。</li><li>用 Safari 打开电脑显示的安装地址，按页面安装并信任本机证书，然后打开 HTTPS 学习地址。</li><li>Safari 分享菜单 → 添加到主屏幕。若看到“作为网页 App 打开”，保持开启。</li><li>从主屏幕打开言叶，进入“我的”，等离线状态显示“离线已就绪”。开启飞行模式，关闭并重新打开应用，确认词书仍能使用。</li></ol><p>只通过 HTTP 局域网访问不能启用离线缓存。证书信任与主屏幕添加需要你在手机上完成。下载本机日语语音后，再测试离线朗读。</p><a href="/install" target="_blank">打开本机安装向导 ↗</a>`);}
async function setupOffline(){if(import.meta.env.DEV){offlineStatus='开发预览不缓存，请使用正式启动入口';return;}if(!window.isSecureContext||!('serviceWorker'in navigator)){offlineStatus='需要通过 HTTPS 安装才能离线使用';return;}try{
 const hadController=!!navigator.serviceWorker.controller;
 const reg=await navigator.serviceWorker.register('/sw.js');
 reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&hadController){toast('新版本已准备好，结束学习后关闭所有言叶窗口再打开即可更新');}});});
 const ready=await Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>setTimeout(()=>reject(new Error('离线缓存尚未完成，请保持页面打开后重试')),30000))]);
 const target=navigator.serviceWorker.controller||ready.active;
 const result=await new Promise((resolve,reject)=>{const mc=new MessageChannel();const timer=setTimeout(()=>reject(new Error('离线检查超时，请稍后重试')),5000);mc.port1.onmessage=e=>{clearTimeout(timer);resolve(e.data);};target.postMessage({type:'VERIFY_CACHE'},[mc.port2]);});
 offlineStatus=result.ready?`离线已就绪 · ${baseWords.length.toLocaleString()} 词已保存`:'离线缓存不完整，请联网后重试';
 }catch(e){offlineStatus=e.message||'离线未完成，请联网后重试';}const label=$('#offline-status');if(label)label.textContent=offlineStatus;
}
function quiz(){const pool=kanaRows.slice(0,11).flat().filter(Boolean);kanaQuiz=pool[Math.floor(Math.random()*pool.length)];const opts=[kanaQuiz,...pool.filter(k=>k.r!==kanaQuiz.r).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);showDialog(`<span class="eyebrow">五十音小练习</span><h2 class="quiz-kana" lang="ja">${kanaQuiz[kanaType]}</h2><p class="center">这个假名怎么读？</p><div class="quiz-options">${opts.map(k=>btn(k.r,'kana-answer','secondary',`data-answer="${k.r}"`)).join('')}</div><p id="quiz-feedback" class="center" aria-live="polite"></p>${btn('换一个','kana-quiz','text-button full')}`);}
document.addEventListener('click',async e=>{
 const target=e.target.closest('[data-action]');if(!target){if(!busy&&page==='study'&&e.target.closest('[data-audio-area]')&&!e.target.closest('button,input,form,a,textarea,select,summary'))speak(byId.get(currentSession(state)?.queue[0])?.reading);return;}if(busy)return;const a=target.dataset.action,id=target.dataset.id;
 busy=true;try{
 if(a==='reload')location.reload();
 else if(a==='page')go(target.dataset.page);
 else if(a==='close')modal.close();
 else if(a==='start')await start(target.dataset.kind,target.dataset.mode||'recognize');
 else if(a==='replace-session'){if(pendingStart)await pendingStart();pendingStart=null;}
 else if(a==='resume')await resumeSession(target.dataset.key||'study');
 else if(a==='exit-study')go('home');
 else if(a==='finish'){await commit(setSession(state,state.activeSessionKey||'study',null));lastState=null;go('home');}
 else if(a==='reveal'){revealed=true;render();}
 else if(a==='reading'){target.outerHTML=esc(byId.get(currentSession(state).queue[0]).reading);}
 else if(a==='grade'){if(!revealed)return;stopSpeech();const before=structuredClone(state);await commit(grade(state,currentSession(state).queue[0],Number(target.dataset.rating)));lastState=before;revealed=false;spellingResult=null;render();window.scrollTo(0,0);autoSpeak();}
 else if(a==='undo'&&lastState){await commit(lastState);lastState=null;revealed=false;spellingResult=null;render();toast('已撤销上次评分');}
 else if(a==='favorite'){const favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];await commit({...state,favorites});if(lastState)lastState.favorites=favorites;target.classList.toggle('is-favorite',favorites.includes(id));target.setAttribute('aria-pressed',String(favorites.includes(id)));target.setAttribute('aria-label',favorites.includes(id)?'取消收藏':'收藏单词');if(page==='notebook')$('#list-body').innerHTML=listBody();toast(favorites.includes(id)?'已加入收藏':'已取消收藏');}
 else if(a==='speak'){const w=byId.get(id);if(w)speak(target.dataset.example!==undefined?w.examples[Number(target.dataset.example)].ja:w.reading);}
 else if(a==='test-voice')speak('こんにちは。今日も一緒に日本語を勉強しましょう。');
 else if(a==='select-book'){await commit({...state,settings:{...state.settings,book:id}});go('home');toast('已切换词书，原有学习记录保留');}
 else if(a==='browse-book'){bookFilter=id;notebookFilter='all';search='';limit=60;go('notebook');}
 else if(a==='filter'){notebookFilter=target.dataset.filter;limit=60;render();}
 else if(a==='more'){limit+=60;$('#list-body').innerHTML=listBody();}
 else if(a==='word-detail')detail(byId.get(id));
 else if(a==='save-note'){const notes={...state.notes,[id]:$('#word-note').value};await commit({...state,notes});if(lastState)lastState.notes=notes;toast('笔记已保存');}
 else if(a==='export')await exportBackup();
 else if(a==='import-book'){showDialog(`<h2>导入自己的词书</h2><p>CSV 表头：word,reading,meaning,sentence,translation。前三列必填，也可以用“日语,假名,中文,例句,例句翻译”。JSON 使用词条数组。</p><p><a href="/example-words.csv" download>下载 CSV 示例</a> · <a href="/example-words.json" download>下载 JSON 示例</a></p>${btn('选择词书文件','choose-book','primary full')}`);}
 else if(a==='choose-book')pickFile('.csv,.json',async(file,text)=>{const book='custom-'+Date.now().toString(36);pendingImport={book,words:parseWordImport(text,file.name,book)};showDialog(`<h2>准备导入 ${pendingImport.words.length} 词</h2><label for="book-name">词书名称</label><input id="book-name" maxlength="100" value="${esc(file.name.replace(/\.(json|csv)$/i,''))}"/><p class="quiet">只新增词书，已有学习记录保留。</p>${btn('导入并开始学习','confirm-import','primary full')}`);});
 else if(a==='confirm-import'&&pendingImport){const name=$('#book-name').value.trim();if(!name)throw new Error('请填写词书名称');if(state.customWords.length+pendingImport.words.length>30000)throw new Error('自选词书合计最多 30000 词');await commit({...state,customWords:[...state.customWords,...pendingImport.words],customBooks:[...state.customBooks,{id:pendingImport.book,name}],settings:{...state.settings,book:pendingImport.book}});pendingImport=null;refreshWords();modal.close();go('home');toast('词书已导入');}
 else if(a==='restore')pickFile('.json',async(file,text)=>{pendingRestore=validateBackup(JSON.parse(text));showDialog(`<h2>恢复学习备份</h2><p>备份包含 ${Object.keys(pendingRestore.cards).length} 个已学词、${pendingRestore.favorites.length} 个收藏和 ${pendingRestore.customBooks.length} 本自选词书。恢复会替换这台设备当前的学习数据。</p>${btn('先导出当前数据','export','secondary full')}${btn('确认恢复此备份','confirm-restore','primary full')}`);});
 else if(a==='confirm-restore'&&pendingRestore){await commit(pendingRestore);pendingRestore=null;lastState=null;refreshWords();modal.close();go('home');toast('备份已恢复');}
 else if(a==='sources')sourceDialog();
 else if(a==='install-help')installDialog();
 else if(a==='check-offline'){await setupOffline();toast(offlineStatus);}
 else if(a==='kana-type'){kanaType=target.dataset.type;render();}
 else if(a==='kana-speak')speak(target.dataset.text);
 else if(a==='kana-quiz')quiz();
 else if(a==='kana-answer'){const correct=target.dataset.answer===kanaQuiz.r;$('#quiz-feedback').textContent=correct?'✓ 答对了！':`再记一下，读作 ${kanaQuiz.r}`;$('#quiz-feedback').className=`center ${correct?'correct':'wrong'}`;speak(kanaQuiz.h);}
 }catch(err){toast(err.message||'操作未完成，请重试');}finally{busy=false;}
});
document.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;limit=60;$('#list-body').innerHTML=listBody();}});
document.addEventListener('change',async e=>{const id=e.target.id;if(id==='book-filter'){bookFilter=e.target.value;limit=60;$('#list-body').innerHTML=listBody();return;}if(!['goal','showReading','autoAudio','theme','voice','rate'].includes(id))return;if(busy){render();return;}busy=true;try{let value=['goal','rate'].includes(id)?Number(e.target.value):['showReading','autoAudio'].includes(id)?e.target.checked:id==='theme'?(e.target.checked?'dark':'light'):e.target.value;await commit({...state,settings:{...state.settings,[id]:value}});render();}catch(err){toast(err.message);render();}finally{busy=false;}});
document.addEventListener('submit',e=>{if(e.target.id==='spelling-form'){e.preventDefault();const value=$('#spelling').value;if(!value.trim()){toast('先输入假名，或点“直接看答案”');return;}spellingResult=acceptsReading(value,byId.get(currentSession(state).queue[0]));revealed=true;render();}});
document.addEventListener('keydown',e=>{if(e.isComposing||modal.open||/INPUT|TEXTAREA|SELECT|BUTTON/.test(e.target.tagName)||page!=='study')return;if(e.code==='Space'&&!revealed){e.preventDefault();$('[data-action="reveal"]')?.click();}else if(revealed&&['1','2','3','4'].includes(e.key))$(`[data-rating="${e.key}"]`)?.click();});
window.addEventListener('hashchange',()=>{const p=location.hash.slice(1)||'home';if(p!==page&&state){page=['home','books','notebook','settings','stats','kana','study'].includes(p)?p:'home';if(page==='study'&&!currentSession(state))page='home';stopSpeech();lastState=null;revealed=false;render();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopSpeech();else if(stale)toast('另一窗口更新了记录，请刷新后继续');else if(state&&page!=='study')render();});
async function boot(){try{const [w,b]=await Promise.all([fetch('/data/words.json').then(r=>{if(!r.ok)throw new Error('词库加载失败');return r.json();}),fetch('/data/books.json').then(r=>{if(!r.ok)throw new Error('词书加载失败');return r.json();}),openDB()]);baseWords=w;baseBooks=b;state=migrateState(await readState()||initialState());refreshWords();if(!books().some(b=>b.id===state.settings.book))state.settings.book='N5';if(state.session?.queue.some(id=>!byId.has(id)))state.session=null;for(const [key,ss] of Object.entries(state.practiceSessions)){if(ss?.queue.some(id=>!byId.has(id)))state.practiceSessions[key]=null;}await saveState(state);page=location.hash.slice(1)||'home';if(!['home','books','notebook','settings','stats','kana','study'].includes(page)||page==='study'&&!currentSession(state))page='home';render();setupOffline();}catch(e){app.innerHTML=`<main class="boot-error"><h1>暂时没能打开单词本</h1><p>${esc(e.message)}</p><p>首次使用请保持网络连接，并允许 Safari 保存网站数据。请勿用无痕模式长期学习。</p><button class="primary" data-action="reload">重新打开</button></main>`;}}
boot();
